apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info

    [INPUT]
        Name         tail
        Path         /var/log/containers/*.log
        Tag          kube.*
        Refresh_Interval 5

    [OUTPUT]
        Name         es
        Host         elasticsearch
        Port         9200
        Index        fluent-bit
        Logstash_Format On
        Suppress_Type_Name On
        Time_Key     @timestamp

