apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>EFK Sample App</title>
    </head>
    <body>
      <h1>EFK Sample Application</h1>
      <p>Deployed using Helm and Argo CD</p>
      <p>Logs are shipped to Elasticsearch and visualized in Kibana by abhi</p>
    </body>
    </html>
